name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bugman-007
          template: classic
          
          # HIDE HEADER & BASE STATS:
          # Setting this to empty ("") completely removes the avatar, 
          # username, joined date, followers, and the footer.
          base: header
          config_timezone: America/New_York

          # PULL REQUEST STATES:
          # Shows the ratio of open vs. merged PRs
          plugin_followup: yes
          plugin_followup_sections: pull-requests

          # KEEP COMMIT STATS:
          plugin_lines: yes
          plugin_lines_history_limit: 1

          # KEEP COMMIT CALENDAR:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
